language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-aqua' ]; then cd .. && eval "mv $currentfolder generator-aqua" && cd generator-aqua; fi

